<?php

declare(strict_types=1);

namespace DeployEcommerce\UrlRewriteImportExport\Model\UrlRewrite;

/**
 * Decides which autogenerated rewrite may keep the generated slot for an entity.
 *
 * url_rewrite is unique on (request_path, store_id) only, so nothing stops two rows from
 * claiming is_autogenerated = 1 for the same (entity_type, entity_id, store_id) — an old
 * path plus the current one, for instance, after a url_key change. Magento's category and
 * product collections LEFT JOIN that table on entity_id and then index the result by entity
 * id, so a second generated row makes the join return two rows and the collection throws
 * "Item (...) with the same ID ... already exists", taking the menu, top navigation and
 * sitemaps down with it.
 *
 * Newest wins: the highest url_rewrite_id is the most recently generated path, i.e. the one
 * matching the entity's current url_key. Losers stay reachable as 301 redirects to the
 * winner — the same shape core produces when a url_key changes.
 */
class DuplicateAutogeneratedResolver
{
    /**
     * @param array<int,array<string,mixed>> $rows Autogenerated rows, each with
     *        url_rewrite_id, entity_type, entity_id, store_id and request_path.
     * @return array<int,array{url_rewrite_id:int,target_path:string}> Rows to demote,
     *         each with the request_path of the winner it should now redirect to.
     */
    public function resolve(array $rows): array
    {
        $groups = [];
        foreach ($rows as $row) {
            $key = $row['entity_type'] . '|' . $row['entity_id'] . '|' . $row['store_id'];
            $groups[$key][] = $row;
        }

        $demotions = [];
        foreach ($groups as $group) {
            if (count($group) < 2) {
                continue;
            }

            usort(
                $group,
                static fn (array $a, array $b): int
                    => (int) $a['url_rewrite_id'] <=> (int) $b['url_rewrite_id']
            );
            $winner = array_pop($group);

            foreach ($group as $loser) {
                $demotions[] = [
                    'url_rewrite_id' => (int) $loser['url_rewrite_id'],
                    'target_path' => (string) $winner['request_path'],
                ];
            }
        }

        return $demotions;
    }
}
