<?php

declare(strict_types=1);

namespace DeployEcommerce\UrlRewriteImportExport\Model\UrlRewrite;

use DeployEcommerce\UrlRewriteImportExport\Model\Schema\ColumnProvider;
use Magento\Framework\App\ResourceConnection;

/**
 * Enforces "one autogenerated rewrite per entity per store" over the whole table.
 *
 * Run after an import: a CSV can reintroduce an old generated path that no longer collides
 * with anything on the unique (request_path, store_id) key, and a raw INSERT bypasses
 * UrlPersist::replace() — which is the only thing that normally deletes superseded rows.
 * Working on the finished table instead of on individual CSV rows keeps the outcome
 * independent of row order, and repairs rows that were already broken before this ran.
 *
 * @see DuplicateAutogeneratedResolver for the winner/loser rule.
 */
class DuplicateAutogeneratedFixer
{
    private const UPDATE_CHUNK = 500;

    public function __construct(
        private readonly ResourceConnection $resourceConnection,
        private readonly ColumnProvider $columnProvider,
        private readonly DuplicateAutogeneratedResolver $resolver
    ) {
    }

    /**
     * @param bool $dryRun Report how many rows would be demoted without writing.
     * @return int Number of rows demoted to 301 redirects.
     */
    public function fix(bool $dryRun = false): int
    {
        $connection = $this->resourceConnection->getConnection();
        $table = $this->columnProvider->getTableName();

        $duplicateKeys = $connection->select()
            ->from(['d' => $table], ['entity_type', 'entity_id', 'store_id'])
            ->where('d.is_autogenerated = ?', 1)
            ->group(['d.entity_type', 'd.entity_id', 'd.store_id'])
            ->having('COUNT(*) > 1');

        $rows = $connection->fetchAll(
            $connection->select()
                ->from(['ur' => $table], ['url_rewrite_id', 'entity_type', 'entity_id', 'store_id', 'request_path'])
                ->joinInner(
                    ['dup' => new \Zend_Db_Expr('(' . $duplicateKeys->assemble() . ')')],
                    'dup.entity_type = ur.entity_type'
                    . ' AND dup.entity_id = ur.entity_id'
                    . ' AND dup.store_id = ur.store_id',
                    []
                )
                ->where('ur.is_autogenerated = ?', 1)
        );

        $demotions = $this->resolver->resolve($rows);
        if ($demotions === [] || $dryRun) {
            return count($demotions);
        }

        // One UPDATE per winning path, so a group of N losers costs one statement.
        $idsByTarget = [];
        foreach ($demotions as $demotion) {
            $idsByTarget[$demotion['target_path']][] = $demotion['url_rewrite_id'];
        }

        foreach ($idsByTarget as $targetPath => $ids) {
            foreach (array_chunk($ids, self::UPDATE_CHUNK) as $chunk) {
                $connection->update(
                    $table,
                    [
                        'is_autogenerated' => 0,
                        'redirect_type' => 301,
                        'target_path' => $targetPath,
                    ],
                    ['url_rewrite_id IN (?)' => $chunk]
                );
            }
        }

        return count($demotions);
    }
}
