<?php

declare(strict_types=1);

use DeployEcommerce\UrlRewriteImportExport\Model\UrlRewrite\DuplicateAutogeneratedResolver;

beforeEach(function () {
    $this->resolver = new DuplicateAutogeneratedResolver();
});

/**
 * @param array<string,mixed> $overrides
 * @return array<string,mixed>
 */
function autogeneratedRow(int $id, string $requestPath, array $overrides = []): array
{
    return array_merge([
        'url_rewrite_id' => $id,
        'entity_type' => 'category',
        'entity_id' => 4147,
        'store_id' => 1,
        'request_path' => $requestPath,
    ], $overrides);
}

it('demotes nothing when every entity has a single generated rewrite', function () {
    $rows = [
        autogeneratedRow(1, 'audio/optical-cables'),
        autogeneratedRow(2, 'networking', ['entity_id' => 4039]),
    ];

    expect($this->resolver->resolve($rows))->toBe([]);
});

it('keeps the newest row and points the older one at it', function () {
    // The real shape of the Kenable failure: parent url_key lost a trailing hyphen,
    // the stale child rewrite was reinserted and never cleaned up.
    $rows = [
        autogeneratedRow(525079, 'audio/digital-audio-/optical-cables'),
        autogeneratedRow(1608642, 'audio/digital-audio/optical-cables'),
    ];

    expect($this->resolver->resolve($rows))->toBe([
        ['url_rewrite_id' => 525079, 'target_path' => 'audio/digital-audio/optical-cables'],
    ]);
});

it('ignores the order rows arrive in', function () {
    $rows = [
        autogeneratedRow(1608642, 'audio/digital-audio/optical-cables'),
        autogeneratedRow(525079, 'audio/digital-audio-/optical-cables'),
    ];

    expect($this->resolver->resolve($rows))->toBe([
        ['url_rewrite_id' => 525079, 'target_path' => 'audio/digital-audio/optical-cables'],
    ]);
});

it('demotes every loser when an entity has more than two generated rewrites', function () {
    $rows = [
        autogeneratedRow(10, 'one'),
        autogeneratedRow(20, 'two'),
        autogeneratedRow(30, 'three'),
    ];

    expect($this->resolver->resolve($rows))->toBe([
        ['url_rewrite_id' => 10, 'target_path' => 'three'],
        ['url_rewrite_id' => 20, 'target_path' => 'three'],
    ]);
});

it('treats each store as its own slot', function () {
    $rows = [
        autogeneratedRow(1, 'optical-cables', ['store_id' => 1]),
        autogeneratedRow(2, 'de/optical-cables', ['store_id' => 2]),
    ];

    expect($this->resolver->resolve($rows))->toBe([]);
});

it('treats each entity type as its own slot', function () {
    $rows = [
        autogeneratedRow(1, 'optical-cables', ['entity_type' => 'category']),
        autogeneratedRow(2, 'optical-cable.html', ['entity_type' => 'product']),
    ];

    expect($this->resolver->resolve($rows))->toBe([]);
});

it('handles string ids and store ids as the database returns them', function () {
    $rows = [
        ['url_rewrite_id' => '525079', 'entity_type' => 'category', 'entity_id' => '4147', 'store_id' => '1', 'request_path' => 'old'],
        ['url_rewrite_id' => '1608642', 'entity_type' => 'category', 'entity_id' => '4147', 'store_id' => '1', 'request_path' => 'new'],
    ];

    expect($this->resolver->resolve($rows))->toBe([
        ['url_rewrite_id' => 525079, 'target_path' => 'new'],
    ]);
});
