<?php

declare(strict_types=1);

use DeployEcommerce\UrlRewriteImportExport\Model\Csv\HeaderValidator;

beforeEach(function () {
    $this->validator = new HeaderValidator();
    // The real url_rewrite columns, in DB order.
    $this->dbColumns = [
        'url_rewrite_id', 'entity_type', 'entity_id', 'request_path', 'target_path',
        'redirect_type', 'store_id', 'description', 'is_autogenerated', 'metadata',
    ];
});

it('accepts a header that exactly mirrors the database', function () {
    expect($this->validator->isImportable($this->dbColumns, $this->dbColumns))->toBeTrue();
});

it('accepts a header that omits nullable columns', function () {
    $header = ['entity_type', 'entity_id', 'request_path', 'target_path', 'store_id'];
    expect($this->validator->isImportable($header, $this->dbColumns))->toBeTrue();
});

it('flags columns that do not exist in the database', function () {
    $header = ['request_path', 'target_path', 'bogus_column', 'store_id'];
    expect($this->validator->unknownColumns($header, $this->dbColumns))->toBe(['bogus_column']);
});

it('rejects a header containing an unknown column', function () {
    $header = ['request_path', 'nope'];
    expect($this->validator->isImportable($header, $this->dbColumns))->toBeFalse();
});

it('rejects an empty header', function () {
    expect($this->validator->isImportable([], $this->dbColumns))->toBeFalse();
});

it('reports database columns the csv does not provide', function () {
    $header = ['request_path', 'target_path', 'store_id'];
    expect($this->validator->missingColumns($header, $this->dbColumns))
        ->toContain('url_rewrite_id')
        ->toContain('metadata');
});

it('ignores surrounding whitespace in column names', function () {
    $header = [' request_path ', 'store_id'];
    expect($this->validator->unknownColumns($header, $this->dbColumns))->toBe([]);
});
